import { skill, type ActoviqSkillDefinition } from 'actoviq-agent-sdk';

export function createClosedLoopNetlistDesignSkill(): ActoviqSkillDefinition {
  return skill({
    name: 'closed-loop-netlist-design',
    description: 'Use the existing ReAct loop plus repo tools to design, validate, simulate, and refine the netlist.',
    whenToUse: 'Use for the main design stage that turns the architecture plan into a final simulated netlist.',
    argumentHint: 'A stage packet with absolute paths, iteration budget, and artifact requirements.',
    prompt: [
      'You are executing /closed-loop-netlist-design.',
      'Use the existing ReAct loop and the provided tools to complete a best-effort closed loop: choose parameters, edit the netlist, validate it, simulate it, and iterate.',
      'Always leave a final netlist, a concise design note, and a step-by-step detailed design report on disk, even when some metrics remain unmet.',
      'The detailed design report must explain the requirement interpretation, topology choice, functional blocks, signal flow, node names, device roles, parameter equations, simulation setup, measured results, limitations, and whether a template was reused or replaced.',
      'If a module-plan.json is provided and the strategy is partitioned, design module files first and then compose the final flat netlist from those module files.',
      'Always write module-manifest.json beside the final netlist. It must list the module order, interface nets, shared nets, module files, and component_names that exactly match the primitive instance names in design.final.cir.',
      'For partitioned designs, every module section in design.final.cir must start with "* MODULE <order>: <snake_case_name>" so renderers can reuse the design-time partition without guessing.',
      'Module boundaries are named nets, not standalone labels: shared nets such as in, out, vdd, 0, rf_out, det_out, and lpf_out must appear as real component terminals.',
      'Do not reuse the final output node as an intermediate module output; use the planned chain nets such as rf_out, det_out, and bb_out, then reserve alarm_n/out only for the final output module.',
      'Prefix local nets inside each module to avoid accidental cross-module shorts.',
      '',
      'Primitive-only hard gate:',
      '- Every SPICE instance line in the final netlist must start with one of R, C, L, Q, M, D, V, or I.',
      '- Do not use X, E, F, G, H, B, A, or U instance prefixes.',
      '- Do not use ideal op-amps, VCVS/VCCS, behavioral sources, or subcircuits.',
      '- Do not write standalone node-label lines such as "alarm_n c 0"; connect named nodes with real primitive components only.',
      '- If an op-amp, comparator, limiter, or alarm is needed, approximate it with transistor/diode/resistor/capacitor primitives and document the limitation.',
      '- After writing design.final.cir, run strict_param_check and validate_netlist_primitives. If either result is not ok, edit the netlist and rerun before ending.',
      '- After run_dual_analysis, inspect data.ok, evaluation.pass, missing_metrics, failed_metrics, and gaps. Tool transport success alone is not verification success.',
      '- If metrics are missing or failed because of analysis cards or .meas syntax, repair the analysis/.meas/.print directives and rerun.',
      '',
      'Stage packet:',
      '$ARGUMENTS',
    ].join('\n'),
    allowedTools: [
      'Read',
      'Write',
      'Edit',
      'Glob',
      'Grep',
      'list_available_templates',
      'copy_template_netlist',
      'list_gmid_models',
      'gmid_size_device',
      'strict_param_check',
      'validate_netlist_primitives',
      'run_dual_analysis',
      'patch_netlist',
    ],
    source: 'custom',
    loadedFrom: 'custom',
  });
}
