import type { JobPaths, WorkflowStage } from './circuitDesignWorkflow.js';

function buildStages(paths: JobPaths, requirement: string): WorkflowStage[] {
  return [
    {
      key: 'solution-analyst',
      label: '1. Solution Analyst',
      agentName: 'solution-analyst',
      skillName: 'requirements-to-spec',
      category: 'planning',
      expectedArtifacts: [
        { label: 'requirements brief', path: (p) => p.requirementBriefPath },
        { label: 'raw spec', path: (p) => p.specRawPath },
        { label: 'normalized spec', path: (p) => p.specNormalizedPath },
      ],
      buildPrompt: (p) => [
        'Authoritative requirement text:',
        requirement,
        '',
        'If reading the requirement file fails, continue from the inline requirement text above.',
        'Do not waste tool calls on path-format retries.',
        'For physically limited circuits such as LDOs, keep assumed targets realistic. Linear-regulator efficiency cannot exceed Vout/Vin.',
        '',
        '目标: 将用户自然语言需求转成工程 brief 和可计算 spec。',
        `输入需求文件: ${p.userRequirementPath}`,
        `输出 brief: ${p.requirementBriefPath}`,
        `输出 raw spec JSON: ${p.specRawPath}`,
        `输出 normalized spec JSON: ${p.specNormalizedPath}`,
        '',
        '请先阅读需求文件，并创建以下产物:',
        '1. requirements-brief.md',
        '内容要求: 需求理解、设计目标、关键指标、假设、风险、推荐电路域。',
        '2. spec.raw.json',
        '至少包含这些字段:',
        '{',
        '  "project_name": string,',
        '  "domain": string,',
        '  "recommended_template": string | null,',
        '  "input_node": string,',
        '  "output_node": string,',
        '  "targets": { "metric_name": { "min"?: number, "max"?: number } },',
        '  "constraints": Record<string, string | number | boolean>,',
        '  "notes": string[]',
        '}',
        '3. 调用 normalize_spec，将 spec.raw.json 归一化到 spec.normalized.json。',
        '',
        '规则:',
        '- prose 用中文。',
        '- metric key 和 JSON key 用英文 snake_case。',
        '- 优先落到本地仓库已有支持的电路域: opamp, oscillator, lna_rf, power, filter。',
        '- 如果用户没有明确给出模板、节点名或指标，必须做出合理假设并写入 brief 与 notes。',
      ].join('\n'),
    },
    {
      key: 'doc-writer',
      label: '2. Doc Writer',
      agentName: 'doc-writer',
      skillName: 'technical-doc-package',
      category: 'planning',
      expectedArtifacts: [
        { label: 'technical solution', path: (p) => p.technicalSolutionPath },
        { label: 'execution checklist', path: (p) => p.executionChecklistPath },
      ],
      buildPrompt: (p) => [
        'Hard execution rules for this stage:',
        '- Read only the brief and normalized spec paths listed below.',
        '- Do not call Glob, Grep, or any project exploration tools.',
        '- Write exactly the two requested markdown files using their absolute output paths.',
        '- Keep each file under 70 lines and avoid large tables.',
        '- Stop after both files exist.',
        '',
        '目标: 基于已结构化的需求，写出技术方案文档和执行清单。',
        `输入 brief: ${p.requirementBriefPath}`,
        `输入 normalized spec: ${p.specNormalizedPath}`,
        `输出 technical solution: ${p.technicalSolutionPath}`,
        `输出 execution checklist: ${p.executionChecklistPath}`,
        '',
        '请创建两个文件:',
        '1. technical-solution.md',
        '内容要求: 方案概述、候选技术路线、推荐路线、关键权衡、可复用仓库能力、交付物。',
        '2. execution-checklist.md',
        '内容要求: 按阶段列出需要完成的动作、输入和输出文件。',
        '',
        '规则:',
        '- 不要写泛泛而谈的介绍，面向工程执行。',
        '- 明确指出为何该需求适合走 actoviq-agent-sdk workflow。',
        '- 文档用中文，路径和文件名保持原样。',
        '- 必须同时创建两个目标文件；如果其中一个缺失，不要结束本阶段。',
      ].join('\n'),
    },
    {
      key: 'librarian',
      label: '3. Librarian',
      agentName: 'librarian',
      skillName: 'asset-reuse-plan',
      category: 'planning',
      expectedArtifacts: [
        { label: 'asset reuse plan', path: (p) => p.assetReusePlanPath },
        { label: 'template netlist', path: (p) => p.templateNetlistPath },
      ],
      buildPrompt: (p) => [
        'Hard execution rules for this stage:',
        '- Call describe_project_assets and list_available_templates once each.',
        '- Read only the brief, normalized spec, and the selected template if needed.',
        '- Write asset-reuse-plan.md as a concise markdown file: no tables, 80 lines maximum.',
        '- Use copy_template_netlist(template_name, output_path) to create template.cir; never paste the netlist with Write.',
        '- Stop after asset-reuse-plan.md and template.cir both exist.',
        '',
        '目标: 复用当前项目内置 bundled assets 的能力，并准备一个最合适的起始 netlist 模板。',
        `输入 brief: ${p.requirementBriefPath}`,
        `输入 normalized spec: ${p.specNormalizedPath}`,
        `输出 asset reuse plan: ${p.assetReusePlanPath}`,
        `输出 copied template: ${p.templateNetlistPath}`,
        '',
        '请使用 describe_project_assets 和 list_available_templates 检查可复用能力。',
        '然后:',
        '1. 写出 asset-reuse-plan.md',
        '内容要求: 当前 bundled assets 提供了哪些模板、脚本和校验能力，为什么适合该需求，以及对应到哪个工作流阶段。',
        '2. 选择最合适的模板并复制到 template.cir。',
        '',
        '规则:',
        '- 如果 raw spec 中已经给出了 recommended_template，优先验证它是否合理。',
        '- 如果没有绝对匹配模板，也要选一个最接近的模板作为起点，并在文档中解释改造点。',
        '- 输出文档用中文。',
      ].join('\n'),
    },
    {
      key: 'architect',
      label: '4. Architect',
      agentName: 'architect',
      skillName: 'architecture-plan',
      category: 'planning',
      expectedArtifacts: [
        { label: 'architecture', path: (p) => p.architecturePath },
        { label: 'verification plan', path: (p) => p.verificationPlanPath },
        { label: 'module plan', path: (p) => p.modulePlanPath },
      ],
      buildPrompt: (p) => [
        'Hard execution rules for this stage:',
        '- Read only the listed input files.',
        '- Do not call Glob, Grep, or exploration tools.',
        '- Write exactly architecture.md and verification-plan.md with the absolute output paths below.',
        '- Keep each file under 90 lines and avoid large tables.',
        '- Stop after both files exist.',
        '',
        '目标: 定义可执行的技术架构、参数预算和验证方案。',
        `输入 brief: ${p.requirementBriefPath}`,
        `输入 technical solution: ${p.technicalSolutionPath}`,
        `输入 asset reuse plan: ${p.assetReusePlanPath}`,
        `输入 normalized spec: ${p.specNormalizedPath}`,
        `输入 template netlist: ${p.templateNetlistPath}`,
        `输出 architecture: ${p.architecturePath}`,
        `输出 verification plan: ${p.verificationPlanPath}`,
        '',
        '请写出:',
        '1. architecture.md',
        '内容要求: 选定拓扑、关键器件/参数预算、节点命名、预期 tradeoff、从模板到最终设计的改造策略。',
        '2. verification-plan.md',
        '内容要求: 每个关键指标如何通过仿真验证，使用哪些分析和输出文件。',
        '',
        '规则:',
        '- 面向后续 netlist designer 直接执行。',
        '- 如果 spec 的节点命名不合理，可以在文档中指出推荐命名，但不要破坏已有 JSON。',
        '- 必须真正写出 architecture.md 和 verification-plan.md 后再停止。',
        '- 先用 Write 工具落盘，再输出任何总结。',
      ].join('\n'),
    },
    {
      key: 'netlist-designer',
      label: '5. Netlist Designer',
      agentName: 'netlist-designer',
      skillName: 'closed-loop-netlist-design',
      category: 'execution',
      expectedArtifacts: [
        { label: 'final netlist', path: (p) => p.designFinalPath },
        { label: 'module manifest', path: (p) => p.moduleManifestPath },
        { label: 'design notes', path: (p) => p.designNotesPath },
        { label: 'detailed design report', path: (p) => p.detailedDesignReportPath },
        { label: 'strict check json', path: (p) => p.strictCheckPath },
        { label: 'primitive check json', path: (p) => p.primitiveCheckPath },
      ],
      buildPrompt: (p) => [
        '目标: 使用现成 ReAct agent 和本地工具完成网表设计到仿真的闭环。',
        `输入 normalized spec: ${p.specNormalizedPath}`,
        `输入 architecture: ${p.architecturePath}`,
        `输入 verification plan: ${p.verificationPlanPath}`,
        `输入 template netlist: ${p.templateNetlistPath}`,
        `输出 final netlist: ${p.designFinalPath}`,
        `输出 design notes: ${p.designNotesPath}`,
        `可选 patch plan path: ${p.patchPlanPath}`,
        `Output detailed design report: ${p.detailedDesignReportPath}`,
        `strict check output: ${p.strictCheckPath}`,
        `primitive check output: ${p.primitiveCheckPath}`,
        `simulation work dir: ${p.simulationDir}`,
        `module manifest output: ${p.moduleManifestPath}`,
        '',
        '执行要求:',
        '1. 从 template.cir 出发，生成 design.final.cir。',
        '2. 如果电路含有有源器件，尽量调用 list_gmid_models / gmid_size_device 获得尺寸初值。',
        '3. 至少运行 strict_param_check 和 validate_netlist_primitives。',
        '4. 尝试运行 run_dual_analysis(work_dir=simulationDir, netlist_path=design.final.cir, spec_path=spec.normalized.json)。',
        '5. 如果仿真失败或指标不满足，迭代修改网表；可以直接编辑，也可以创建 patch-plan.json 并调用 patch_netlist。',
        '6. 最多做 3 轮主要迭代，但一定要留下可用的最终网表和 design-notes.md。',
        '',
        'design-notes.md 至少包含:',
        '- 选定器件和参数',
        '- 主要迭代记录',
        '- 当前仿真状态或阻塞项',
        '- 后续最值得继续优化的方向',
        '',
        'detailed-design-report.md 至少包含:',
        '- 需求理解、拓扑选择、功能分块和信号流',
        '- 节点命名、模块边界、器件作用和关键参数计算',
        '- 仿真设置、测量结果、已知限制和下一步优化',
        '- 是否复用了模板，以及从模板到最终设计改了什么',
        '',
        '规则:',
        '- 如果 ngspice 或模型不可用，不要卡死；完成 best-effort 网表并明确记录阻塞。',
        '- prose 用中文，SPICE/JSON 保持英文。',
        '- 本阶段不要调用 netlist_to_json、render_netlistsvg、render_schemdraw、render_agent_svg。',
        '- 只要 final netlist、design notes、detailed design report、检查结果已经就绪，就停止本阶段。',
      ].join('\n'),
    },
    {
      key: 'simulation-verifier',
      label: '6. Simulation Verifier',
      agentName: 'simulation-verifier',
      skillName: 'final-verification-review',
      category: 'execution',
      requiresConfirmation: false,
      expectedArtifacts: [{ label: 'final review', path: (p) => p.finalReviewPath }],
      buildPrompt: (p) => [
        '目标: 对最终设计做收口验证，形成文件化评审意见。',
        `输入 normalized spec: ${p.specNormalizedPath}`,
        `输入 final netlist: ${p.designFinalPath}`,
        `输入 design notes: ${p.designNotesPath}`,
        `输入 detailed design report: ${p.detailedDesignReportPath}`,
        `strict check output path: ${p.strictCheckPath}`,
        `primitive check output path: ${p.primitiveCheckPath}`,
        `verification simulation dir: ${p.finalSimulationDir}`,
        `输出 final review: ${p.finalReviewPath}`,
        '',
        '请执行:',
        '1. 重新检查 final netlist，必要时重跑 strict_param_check 和 validate_netlist_primitives。',
        '2. 尝试在 final-simulation 目录重跑 run_dual_analysis。',
        '3. 写 final-review.md，给出 pass/fail、证据文件、剩余风险、建议下一步。',
        '',
        '规则:',
        '- 这是验证阶段，不要重新发明拓扑。',
        '- 如果某个检查无法运行，也要写清楚原因和影响。',
        '- review 用中文。',
      ].join('\n'),
    },
    {
      key: 'netlistsvg-renderer',
      label: '7. Netlistsvg Renderer',
      agentName: 'netlistsvg-renderer',
      skillName: 'render-schematic-netlistsvg',
      category: 'rendering',
      expectedArtifacts: [
        { label: 'design json', path: (p) => p.designJsonPath },
        { label: 'netlistsvg svg', path: (p) => p.netlistsvgPath },
        { label: 'netlistsvg geometry report', path: (p) => p.netlistsvgGeometryPath },
        { label: 'netlistsvg layout report', path: (p) => p.netlistsvgLayoutReportPath },
        { label: 'netlistsvg notes', path: (p) => p.netlistsvgNotesPath },
      ],
      buildPrompt: (p) => [
        '目标: 使用 netlistsvg 渲染原理图。',
        `输入 final netlist: ${p.designFinalPath}`,
        `输入 raw spec: ${p.specRawPath}`,
        `输出 design json: ${p.designJsonPath}`,
        `输出 svg: ${p.netlistsvgPath}`,
        `输出 notes: ${p.netlistsvgNotesPath}`,
        '',
        '执行要求:',
        '1. 先从 spec.raw.json 中读取 input_node 和 output_node。',
        '2. 如果 design.json 不存在或需要重建，调用 netlist_to_json。',
        '3. 调用 render_netlistsvg 产出 SVG；大电路的分区渲染、几何报告和布局报告由该工具后端自动处理。',
        '4. 不要手写 Python/JSON/SVG，不要手动拆分模块文件，不要调用 Write/Edit/Glob/Grep 做临时分区。',
        '5. render_netlistsvg 返回后立刻停止；如果 notes 缺失，workflow 会用本地 fallback 补齐。',
      ].join('\n'),
    },
    {
      key: 'workflow-lead',
      label: '8. Workflow Lead',
      agentName: 'workflow-lead',
      skillName: 'handoff-summary',
      category: 'summary',
      expectedArtifacts: [{ label: 'final summary', path: (p) => p.finalSummaryPath }],
      buildPrompt: (p) => [
        '目标: 汇总本次工作流的最终交付。',
        `输入需求: ${p.userRequirementPath}`,
        `输入 brief: ${p.requirementBriefPath}`,
        `输入 technical solution: ${p.technicalSolutionPath}`,
        `输入 asset reuse plan: ${p.assetReusePlanPath}`,
        `输入 architecture: ${p.architecturePath}`,
        `输入 design notes: ${p.designNotesPath}`,
        `输入 detailed design report: ${p.detailedDesignReportPath}`,
        `输入 final review: ${p.finalReviewPath}`,
        `输出 final summary: ${p.finalSummaryPath}`,
        '',
        '请写 final-summary.md，至少包含:',
        '- 用户需求摘要',
        '- 选定方案与复用能力',
        '- 最终网表与验证状态',
        '- netlistsvg SVG 输出及路径',
        '- 剩余风险和下一步建议',
      ].join('\n'),
    },
  ];
}

function withStrictLibrarianPrompt(stages: WorkflowStage[]): WorkflowStage[] {
  return stages.map((stage) => {
    if (stage.key !== 'librarian') {
      return stage;
    }
    return {
      ...stage,
      buildPrompt: (p) => [
        'Goal: select the best bundled starter netlist and prepare a concise reuse plan.',
        `Input brief: ${p.requirementBriefPath}`,
        `Input normalized spec: ${p.specNormalizedPath}`,
        `Output asset reuse plan: ${p.assetReusePlanPath}`,
        `Output copied template: ${p.templateNetlistPath}`,
        '',
        'Hard execution rules:',
        '- Call describe_project_assets and list_available_templates once each.',
        '- Read only the brief, normalized spec, and the selected template if needed.',
        '- Prefer the recommended_template in normalized spec when it is available.',
        '- Write asset-reuse-plan.md as concise Chinese markdown: no tables, 80 lines maximum.',
        '- Use copy_template_netlist with template_name and output_path to create template.cir.',
        '- Never paste template netlist text with Write.',
        '- Stop after asset-reuse-plan.md and template.cir both exist.',
      ].join('\n'),
    };
  });
}

function withRobustCircuitPromptOverrides(stages: WorkflowStage[]): WorkflowStage[] {
  return stages.map((stage) => {
    if (stage.key === 'librarian') {
      return withStrictLibrarianPrompt([stage])[0]!;
    }
    if (stage.key === 'solution-analyst') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: convert the user requirement into an engineering brief and normalized circuit spec.',
          'Write prose artifacts in Chinese; keep JSON keys and metric names in English snake_case.',
          '',
          'Authoritative requirement text:',
          '(read the full text from the input requirement file below)',
          '',
          `Input requirement file: ${p.userRequirementPath}`,
          `Output requirements brief: ${p.requirementBriefPath}`,
          `Output raw spec JSON: ${p.specRawPath}`,
          `Output normalized spec JSON: ${p.specNormalizedPath}`,
          '',
          'Execution:',
          '- Read the requirement file. If the file read fails, continue from the inline requirement text above.',
          '- Read only the requirement file in this stage. Do not read design.final.cir, detailed-design-report.md, manifest.json, render outputs, or any future-stage artifact because they do not exist yet for a new job.',
          '- Do not call Glob, Grep, describe_project_assets, or template tools in this stage.',
          '- Write requirements-brief.md with requirement understanding, assumptions, selected circuit domain, key metrics, and risks.',
          '- Write spec.raw.json with project_name, domain, recommended_template, input_node, output_node, targets, constraints, and notes.',
          '- Call normalize_spec to create spec.normalized.json.',
          '- For complex or multi-stage tasks, include constraints.suggest_partitioned_design=true and name important internal signals in notes.',
          '- Keep assumed targets physically realistic; for example, LDO efficiency cannot exceed Vout/Vin.',
        ].join('\n'),
      };
    }

    if (stage.key === 'doc-writer') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: write a compact technical solution and execution checklist from the structured spec.',
          `Input brief: ${p.requirementBriefPath}`,
          `Input normalized spec: ${p.specNormalizedPath}`,
          `Output technical solution: ${p.technicalSolutionPath}`,
          `Output execution checklist: ${p.executionChecklistPath}`,
          '',
          'Hard execution rules:',
          '- Read only the brief and normalized spec paths above.',
          '- Do not call Glob, Grep, or repository exploration tools.',
          '- Write exactly the two requested markdown files using absolute output paths.',
          '- Use Chinese prose, no large tables, under 70 lines per file.',
          '- Include whether the design should be handled as a single block or partitioned into modules.',
        ].join('\n'),
      };
    }

    if (stage.key === 'architect') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: define an implementation architecture, verification plan, and module partition plan.',
          `Input brief: ${p.requirementBriefPath}`,
          `Input technical solution: ${p.technicalSolutionPath}`,
          `Input asset reuse plan: ${p.assetReusePlanPath}`,
          `Input normalized spec: ${p.specNormalizedPath}`,
          `Input template netlist: ${p.templateNetlistPath}`,
          `Output architecture: ${p.architecturePath}`,
          `Output verification plan: ${p.verificationPlanPath}`,
          `Output module plan JSON: ${p.modulePlanPath}`,
          '',
          'Hard execution rules:',
          '- Read only the listed input files.',
          '- Do not call Glob, Grep, or repository exploration tools.',
          '- Write architecture.md and verification-plan.md in Chinese, under 90 lines each.',
          '- Always write module-plan.json. For simple circuits it may contain one module; for large tasks it must split the circuit into blocks.',
          '',
          'module-plan.json schema:',
          '{',
          '  "strategy": "single_block" | "partitioned",',
          '  "complexity_score": number,',
          '  "shared_nets": ["in", "out", "vdd", "0"],',
          '  "modules": [',
          '    {',
          '      "name": "english_snake_case_module_name",',
          '      "file": "design/modules/01_module_name.cir",',
          '      "purpose": "short purpose",',
          '      "input_nets": ["in", "vdd", "0"],',
          '      "output_nets": ["stage_out"],',
          '      "local_net_prefix": "m1_",',
          '      "verification_targets": ["metric_or_behavior"]',
          '    }',
          '  ],',
          '  "integration_rules": ["flat final netlist only", "connect modules by shared net labels"]',
          '}',
          '',
          'Partitioning guidance:',
          '- Use partitioned strategy when the request has more than about 20 components, RF + baseband + logic, multiple feedback loops, or several verification domains.',
          '- Modules must connect only through named net labels listed in shared_nets or the module input/output nets.',
          '- Do not plan .subckt or X instances unless the primitive gate is explicitly relaxed; this workflow composes a flat final SPICE netlist.',
          '- Require final design.final.cir to be a flat concatenation of primitive instance lines from module files.',
        ].join('\n'),
      };
    }

    if (stage.key === 'netlist-designer') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: design a runnable primitive-only SPICE netlist, validate it, simulate it, and leave concise notes.',
          `Input normalized spec: ${p.specNormalizedPath}`,
          `Input architecture: ${p.architecturePath}`,
          `Input verification plan: ${p.verificationPlanPath}`,
          `Input module plan: ${p.modulePlanPath}`,
          `Input template netlist: ${p.templateNetlistPath}`,
          `Optional module output dir: ${p.modulesDir}`,
          `Output final netlist: ${p.designFinalPath}`,
          `Output module manifest: ${p.moduleManifestPath}`,
          `Output design notes: ${p.designNotesPath}`,
          `Output detailed design report: ${p.detailedDesignReportPath}`,
          `Strict check output: ${p.strictCheckPath}`,
          `Primitive check output: ${p.primitiveCheckPath}`,
          `Simulation work dir: ${p.simulationDir}`,
          '',
          'Primitive-only hard gate:',
          '- Every non-comment SPICE instance line must start with R, C, L, Q, M, D, V, or I.',
          '- Forbidden instance prefixes: X, E, F, G, H, B, A, U.',
          '- Do not use ideal op-amps, VCVS/VCCS, behavioral sources, XSPICE models, or subcircuits.',
          '- Do not write standalone node-label lines such as "alarm_n c 0"; named nodes must appear only as component terminals.',
          '- For op-amp/comparator/alarm behavior, use BJT/MOS/diode/resistor/capacitor approximations.',
          '- Keep required interface names exactly as spec: input node in, output node alarm_n unless spec says otherwise.',
          '',
          'Execution:',
          '- Do not call Task or delegate to subagents. No background circuit designer agents are registered in this workflow.',
          '- Tool budget is strict: do not call list_available_templates, copy_template_netlist, Glob, Grep, or broad repository exploration in this stage.',
          '- Read only the listed input files, template.cir, and module files that you create yourself.',
          '- Keep the first runnable implementation compact. For very large module plans, merge adjacent functions into 5-8 functional sections in design.final.cir while preserving the explicit interface nets in module-manifest.json.',
          '- Prefer writing final netlist, module manifest, design notes, and detailed report directly before running validation; do not spend most tool calls inspecting templates.',
          '- Start from template.cir, then write design.final.cir.',
          '- Read module-plan.json before editing. If strategy is partitioned, write each module into design/modules/*.cir first, then compose design.final.cir as a flat concatenation.',
          '- Always write module-manifest.json during this stage. For single-block designs, write one module; for partitioned designs, list every module in signal-flow order.',
          '- module-manifest.json schema: {"version":"actoviq.module-manifest.v1","strategy":"single_block|partitioned","interface_chain":["in","...","alarm_n"],"shared_nets":["vdd","0"],"modules":[{"name":"snake_case","label":"DISPLAY LABEL","order":1,"file":"design/modules/01_name.cir","purpose":"...","input_nets":["in"],"output_nets":["stage_out"],"shared_nets":["vdd","0"],"local_net_prefix":"mod_","component_names":["R1","C1"]}],"composition":{"mode":"flat_concatenation","module_comment_format":"* MODULE <order>: <name>"}}.',
          '- Every module section in design.final.cir must start with "* MODULE <order>: <module_name>", and every manifest component_names entry must exactly match a primitive instance name in design.final.cir.',
          '- Connect modules only through explicit net labels, for example rf_out, det_out, lpf_out, vdd, and 0. Do not add standalone label-only lines.',
          '- Never reuse the final output node as an intermediate net. For a chain like RF -> detector -> baseband -> comparator, use rf_out/det_out/bb_out internally and reserve alarm_n/out for the final module output only.',
          '- Prefix local internal nets per module using local_net_prefix to avoid accidental shorts across modules.',
          '- In design-notes.md include a Module Integration section listing every shared net and which modules drive or consume it.',
          '- Run strict_param_check and validate_netlist_primitives after every major edit.',
          '- If validate_netlist_primitives data.ok is false, edit design.final.cir and rerun it before stopping.',
          '- Only run run_dual_analysis after primitive validation is ok.',
          '- Treat run_dual_analysis data.ok=false, evaluation.pass=false, failed_metrics, or missing_metrics as a real design/measurement failure to repair.',
          '- Keep exactly one effective .ac sweep; the splitter can merge sweeps, but the source netlist should not depend on duplicate .ac cards.',
          '- Include .meas outputs for every target in spec.targets_eval when practical, and verify that metrics.json contains those names.',
          '- If ngspice rejects dB expressions in .meas, change the measurement method and rerun instead of leaving failed_metrics.',
          '- Stop only after strict validation, primitive validation, and the latest run_dual_analysis have all been inspected.',
          '- Write design-notes.md in Chinese, no tables, 80 lines maximum.',
          '- Write detailed-design-report.md in Chinese as a step-by-step circuit design report, not only a summary.',
          '- detailed-design-report.md must explain requirement interpretation, topology choice, functional blocks, signal flow, node naming, module boundaries, device roles, parameter equations, simulation setup, measured results, limitations, and whether a template was reused or replaced.',
          '- Stop once final netlist, module manifest, design notes, detailed design report, strict JSON, and primitive JSON exist and primitive validation is ok.',
        ].join('\n'),
      };
    }

    if (stage.key === 'simulation-verifier') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: verify the final netlist and write one concise acceptance review.',
          `Input normalized spec: ${p.specNormalizedPath}`,
          `Input final netlist: ${p.designFinalPath}`,
          `Input design notes: ${p.designNotesPath}`,
          `Input detailed design report: ${p.detailedDesignReportPath}`,
          `Strict check output path: ${p.strictCheckPath}`,
          `Primitive check output path: ${p.primitiveCheckPath}`,
          `Verification simulation dir: ${p.finalSimulationDir}`,
          `Output final review: ${p.finalReviewPath}`,
          '',
          'Execution:',
          '- Run strict_param_check, validate_netlist_primitives, and run_dual_analysis.',
          '- Inspect run_dual_analysis data.ok, evaluation.pass, missing_metrics, failed_metrics, and gaps; do not treat tool transport success as verification success.',
          '- If failure is only duplicate analysis cards, rejected .meas syntax, or missing measurement directives, you may edit only analysis/.meas/.print directives and rerun.',
          '- Write exactly one final-review.md to the output path above.',
          '- Keep final-review.md in Chinese, no tables, 70 lines maximum.',
          '- If any check fails, explain the failing tool, exact cause, impact, and next repair step.',
          '- Do not redesign topology or component values in this stage.',
        ].join('\n'),
      };
    }

    if (stage.key === 'netlistsvg-renderer') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: render the schematic with the netlistsvg backend and record geometry quality.',
          `Input final netlist: ${p.designFinalPath}`,
          `Input raw spec: ${p.specRawPath}`,
          `Input module manifest: ${p.moduleManifestPath}`,
          `Output design JSON: ${p.designJsonPath}`,
          `Output SVG: ${p.netlistsvgPath}`,
          `Output geometry report: ${p.netlistsvgGeometryPath}`,
          `Output layout report: ${p.netlistsvgLayoutReportPath}`,
          `Output notes: ${p.netlistsvgNotesPath}`,
          '',
          'Execution:',
          '- Read raw spec for input_node and output_node.',
          '- Call netlist_to_json if design.json is missing or stale, and pass module_manifest_path when module-manifest.json exists.',
          '- Call render_netlistsvg and inspect the returned geometry/layout reports.',
          '- For partitioned circuits, accept only a label-only module overview: module blocks must not be connected by cross-block signal wires or shared rail wires.',
          '- Write netlistsvg-notes.md in Chinese with success/failure status, known crossings/overlaps, and next layout improvement.',
        ].join('\n'),
      };
    }

    if (stage.key === 'workflow-lead') {
      return {
        ...stage,
        buildPrompt: (p) => [
          'Goal: write the final handoff summary.',
          `Input requirement: ${p.userRequirementPath}`,
          `Input brief: ${p.requirementBriefPath}`,
          `Input technical solution: ${p.technicalSolutionPath}`,
          `Input asset reuse plan: ${p.assetReusePlanPath}`,
          `Input architecture: ${p.architecturePath}`,
          `Input module plan: ${p.modulePlanPath}`,
          `Input module manifest: ${p.moduleManifestPath}`,
          `Input design notes: ${p.designNotesPath}`,
          `Input detailed design report: ${p.detailedDesignReportPath}`,
          `Input final review: ${p.finalReviewPath}`,
          `Output final summary: ${p.finalSummaryPath}`,
          '',
          'Hard execution rules:',
          '- Read only the listed input files and render notes needed for path/status evidence.',
          '- Write exactly one final-summary.md using Write with top-level JSON fields: {"file_path":"OUTPUT_PATH","content":"..."}',
          '- Do not call Write with raw-only, markdown-only, or wrapped arguments.',
          '- Keep final-summary.md in Chinese, no tables, 90 lines maximum.',
          '- Clearly state pass/fail status from final-review.md; do not hide failed metrics.',
          '- Include the paths for design.final.cir, module-manifest.json, detailed-design-report.md, final-review.md, and netlistsvg.svg.',
        ].join('\n'),
      };
    }

    return stage;
  });
}

export function createWorkflowStages(paths: JobPaths, requirement: string): WorkflowStage[] {
  return withRobustCircuitPromptOverrides(buildStages(paths, requirement));
}

